sudo: false
dist: trusty
language: c
compiler:
  - gcc
cache:
  directories:
    - $HOME/.cache
notifications:
  email: false
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - re2c
env:
    - BASE=R3.15.5    STATIC=shared ASYN=R4-26 BUSY=R1-6-1 SNCSEQ=2.2.4 CALC=R3-6-1
    - BASE=R3.14.12.6 STATIC=shared ASYN=R4-26 BUSY=R1-6-1 SNCSEQ=2.2.4 CALC=R3-6-1
    
before_install: chmod +x ./.ci/assemble_synApps.sh

install: ./.ci/assemble_synApps.sh
    
    
script: 
  # Build the module
  - make
 
